# @baseUrl = https://localhost:7255
@baseUrl = http://localhost:5162
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMmYyNjAxOS02MGVjLTRkMDItOTQzMy0yNWYyMzY2NzVjY2MiLCJnaXZlbl9uYW1lIjoiS2hvYSIsImZhbWlseV9uYW1lIjoiSHXhu7NuaCIsImp0aSI6ImViNDJlNTFiLTMwNmMtNGUwYi04NjY1LTEzYmUwY2E4MmQxMSIsImV4cCI6MTc1MjQ2NjE4OSwiaXNzIjoiSHV5bmhBbmhLaG9hIiwiYXVkIjoiSHV5bmhBbmhLaG9hIn0._yNnOzFgicrobIXlwaGTovrNoJ7eOvHCLaqId809f88
@hostId = adage

POST {{baseUrl}}/api/{{hostId}}/menu
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "name" : "KHoa",
   "description" : "Lần này thì anh chịu thua em rồi.",
   "sections" : [
      {
         "name" : "1",
         "description" : "Lần này thì anh chịu thua em rồi.",
         "items" : [
            {
               "name" : "1",
               "description" : "Lần này thì anh chịu thua em rồi."
            }
         ]
      }
   ]
}