@baseUrl = http://localhost:5162

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "firstName": "Khoa",
    "lastName":"Huỳnh",
    "email":"anhkhoa@gmail.com",
    "password":"123"
}