@baseUrl = http://localhost:5162

GET {{baseUrl}}/api/Lunch/ListLunch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmODA2YWEyMS0yMDU4LTQyNzctOTYxMS0yZWQ4NzY0YWU3YzMiLCJnaXZlbl9uYW1lIjoiYyIsImZhbWlseV9uYW1lIjoiYyIsImp0aSI6ImMwMWFhMDFhLWVmMTQtNGUwMS1iYjA4LTBiNTJiMjg1NDEyNyIsImV4cCI6MTc1MTU1NjU4MSwiaXNzIjoiSHV5bmhBbmhLaG9hIiwiYXVkIjoiSHV5bmhBbmhLaG9hIn0.KvPPRjIGPfqUVr02Zp_baHsoTl3Mi7lZgRVaOMkjqRg