# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CA_DDD_Project/Mini_Ecomerce_DDD.sln

    - name: Build solution
      run: dotnet build CA_DDD_Project/Mini_Ecomerce_DDD.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test CA_DDD_Project/Mini_Ecomerce_DDD.sln --no-build --configuration Release

